### ISSUE TITLE
package.json issues

### ISSUE THREAD

**Issue by Martyniuk** [uroslazarevic/repo-browser#3]
Not crucial at all, but in **package.json**:
- dependencies contain dev dependencies (types)
- no TS check script

**Comment by uroslazarevic** [comment]
Hello @Martyniuk ,

I am aware of the convention of placing devDeps and deps. At, the end it doesn't matter because a complier will strip all unecessary packages in the build process. That is why, [create react app](https://github.com/facebook/create-react-app/issues/6180) puts the @types libs in deps by default.

**Comment by uroslazarevic** [comment]
@Martyniuk, please let me know if this answer addresses your questions.
Thanks :)
